### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WolfgangKurz** [WolfgangKurz/grabbable#3]
- [x] TypeScript
- [ ] CSS Grid compatible
- [ ] ~HTML Table compatible~
- [x] Function returns Element list
- [x] Remembered position option
- [x] Customizable styles
